version: '3.8'

services:
  db:
    image: mariadb
    hostname: mariadb
    restart: always
    environment:
      - LANG
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MARIADB_AUTO_UPGRADE
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - gibbon-db-data:/var/lib/mysql
      - gibbon-db-log:/var/log/mysql
      - ./db/backup:/backup
      - ./db/backupscripts:/backupscripts
      - /etc/localtime:/etc/localtime:ro
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.db-backup.schedule: "0 2 7-19,23 * * *"
      ofelia.job-exec.db-backup.command: "/backupscripts/simplebackup_hourly.sh"
      ofelia.job-exec.backupreduce-daily.schedule: "@daily"
      ofelia.job-exec.backupreduce-daily.command: "/backupscripts/backupreduce_daily.sh"
      ofelia.job-exec.backupreduce-monthly.schedule: "@monthly"
      ofelia.job-exec.backupreduce-monthly.command: "/backupscripts/backupreduce_monthly.sh"
    networks:
      - default
      - backup
    
  apache:
    build: ./webserver
    hostname: gibbon-apache
    restart: always
    depends_on:
      - php
    environment:
      - GIBBON_SITENAME
      - SERVER_ADMIN_MAIL
      - VIRTUAL_HOST=${GIBBON_SITENAME}
#      - LETSENCRYPT_HOST
#      - LETSENCRYPT_EMAIL
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - gibbon-root:${GIBBON_BASEDIR}
    networks:
      - default
      - webfront

  php:
    build: 
      context: ./php
      dockerfile: Dockerfile
      target: dev
    hostname: gibbon-php
    restart: always
    environment:
      - GIBBON_SITENAME
      - GIBBON_VERSION
#      - GIBBON_DB_HOST=mariadb
#      - GIBBON_DB_PORT=3306
#      - GIBBON_DB_DB=${MYSQL_DATABASE}
#      - GIBBON_DB_USER=${MYSQL_USER}
#      - GIBBON_DB_PASSWORD=${MYSQL_PASSWORD}
      - GIBBON_BASEDIR
    volumes:
      - gibbon-root:${GIBBON_BASEDIR}
      - gibbon-php-sessions:/sessions
    networks:
      - default

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - db
    command: daemon --docker -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime

  smtpd:
    image: namshi/smtp
    restart: always
    depends_on:
      - php
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MAILNAME
      - SMARTHOST_ADDRESS
      - SMARTHOST_PORT
      - SMARTHOST_USER
      - SMARTHOST_PASSWORD
      - SMARTHOST_ALIASES
    networks:
      - default

volumes:
  gibbon-db-data:
  gibbon-db-log:
  gibbon-root:
  gibbon-php-sessions:

networks:
  webfront:
    name: webfront
    external: true
  backup:
    name: backup
    external: true
