#!/bin/sh

# GIBBON_VERSION set in .env file
GIBBON_INSTALLED_VERSION=$(grep "version =" /var/www/html/version.php)

echo "-------------- Checking if a gibbon is up to date ----------------"
if echo "$GIBBON_INSTALLED_VERSION" | grep -q "$GIBBON_VERSION"; then
    echo "-------------- Gibbon is up to date ----------------"
else
    echo "-------------- Downloading gibbon ----------------"
    su -s /bin/sh -c "cd /tmp && wget https://github.com/GibbonEdu/core/releases/download/v${GIBBON_VERSION}/GibbonEduCore-InstallBundle.tar.gz" www-data
    echo "-------------- Moving gibbon into place ----------------"
    su -s /bin/sh -c "mkdir /tmp/Gibbon && tar xfz /tmp/GibbonEduCore-InstallBundle.tar.gz -C /tmp/Gibbon" www-data
    chown www-data:www-data -R /tmp/Gibbon
    rsync -vua /tmp/Gibbon/ ${GIBBON_BASEDIR}
    chown www-data:www-data -R ${GIBBON_BASEDIR}
    # check if index.html exits and remove it on new installations
    if [ -z "$GIBBON_INSTALLED_VERSION" ]; then
      echo "-------------- check index.html  exists ----------------"
      if [ "${GIBBON_BASEDIR}/index.html" ]; then
        echo "---------------- removing index.html ----------------"
        rm ${GIBBON_BASEDIR}/index.html
      else
        echo "-------------- index.html does not exist, everything is fine ----------------"
      fi
    else
        echo "-------------- Upgrade specific tasks  ----------------"
        echo "-------------- cleanup vendor directory ----------------"
        su -s /bin/sh -c "cd ${GIBBON_BASEDIR} && composer clearcache" www-data
        su -s /bin/sh -c "rm -rf ${GIBBON_BASEDIR}/vendor" www-data
        su -s /bin/sh -c "cd ${GIBBON_BASEDIR} && composer install --no-dev" www-data

        echo "-------------- check for upgrade versionspecific actions ----------------"
        if echo ${GIBBON_VERSION} | grep -Eq '^22\.'; then
            echo "---------------- upgrade actions for version 22.xx.xx ----------------"
	    # Note that in the switch to v22 the module Roll Groups has been replaced with Form Groups. If you are updating using this method from a version prior to v22 you will need to run this command too
	    echo "------------------ checking if directory to remove exists ----------------"
	    if [ -d "${GIBBON_BASEDIR}/modules/Roll Groups" ]; then
	        echo "-------------------- removing directory ----------------"
	        rm -rf ${GIBBON_BASEDIR}/modules/Roll\ Groups
	    fi
        fi
    fi
    echo "-------------- temporary files cleanup  ----------------"
    rm /tmp/GibbonEduCore-InstallBundle.tar.gz
    rm -rf /tmp/Gibbon
#    sed -i "s/$databaseServer = .*$/$databaseServer = '${GIBBON_DB_HOST}';/g" ${GIBBON_BASEDIR}/config.php
#    sed -i "s/$databaseUsername = .*$/$databaseUsername = '${GIBBON_DB_USER}';/g" ${GIBBON_BASEDIR}/config.php
#    sed -i "s/$databasePassword = .*$/$databasePassword = '${GIBBON_DB_PASSWORD}';/g" ${GIBBON_BASEDIR}/config.php
#    sed -i "s/$databaseName = .*$/$databaseName = '${GIBBON_DB_DB}';/g" ${GIBBON_BASEDIR}/config.php

fi
