#!/bin/sh

# GIBBON_VERSION set in .env file
GIBBON_INSTALLED_VERSION=$(grep "version =" /var/www/html/version.php)

echo "-------------- Checking if a gibbon is up to date ----------------"
if echo "$GIBBON_INSTALLED_VERSION" | grep -q "$GIBBON_VERSION"; then
    echo "-------------- Gibbon is up to date ----------------"
else
    echo "-------------- Downloading gibbon ----------------"
    su -s /bin/sh -c "cd /tmp && wget https://github.com/GibbonEdu/core/releases/download/v${GIBBON_VERSION}/GibbonEduCore-InstallBundle.tar.gz" www-data
    echo "-------------- Moving gibbon into place ----------------"
    su -s /bin/sh -c "mkdir /tmp/Gibbon && tar xfz /tmp/GibbonEduCore-InstallBundle.tar.gz -C /tmp/Gibbon" www-data
    chown www-data:www-data -R /tmp/Gibbon
    rsync -vua /tmp/Gibbon/ ${GIBBON_BASEDIR}
#    su -s /bin/sh -c "rsync -vua /tmp/core-${GIBBON_VERSION}/ /var/www/html/" www-data
#    su -s /bin/sh -c "rm /tmp/v${GIBBON_VERSION}.tar.gz && rm -rf /tmp/core-${GIBBON_VERSION}" www-data
    chown www-data:www-data -R ${GIBBON_BASEDIR}
    echo "-------------- check index.html  exists ----------------"
    if [ ! -f "${GIBBON_BASEDIR}/index.html" ]; then
      echo "-------------- removeint index.html ----------------"
      rm ${GIBBON_BASEDIR}/index.html
    else
      echo "-------------- index.html does not exist, everything is fine ----------------"
    fi
    sed -i "s/$databaseServer = .*$/$databaseServer = '${GIBBON_DB_HOST}';/g" ${GIBBON_BASEDIR}/config.php
    sed -i "s/$databaseUsername = .*$/$databaseUsername = '${GIBBON_DB_USER}';/g" ${GIBBON_BASEDIR}/config.php
    sed -i "s/$databasePassword = .*$/$databasePassword = '${GIBBON_DB_PASSWORD}';/g" ${GIBBON_BASEDIR}/config.php
    sed -i "s/$databaseName = .*$/$databaseName = '${GIBBON_DB_DB}';/g" ${GIBBON_BASEDIR}/config.php
fi
